version: 2

updates:
- package-ecosystem: pip
  directory: /
  # only update Pipfile.lock to avoid breaking compatibility with python3.4
  versioning-strategy: lockfile-only
  schedule:
    interval: weekly
    day: friday

# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
